apiVersion: v1
kind: Namespace
metadata:
  name: q2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-server
  namespace: q2
  labels:
    app: http-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: http-server
  template:
    metadata:
      labels:
        app: http-server
    spec:
      containers:
      - name: http-server
        image: hatappi/k8s-training:v1.3
        imagePullPolicy: Always
        args:
          - http-server
        ports:
        - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: http-server
  namespace: q2
spec:
  selector:
    app: http-server
  ports:
  - protocol: TCP
    port: 8888
    targetPort: 8888
